version: "3"
services:
  db_prod:
    image: postgres
    volumes:
      - psgl_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${EXPENSES_DATABASE_PASSWORD}
    ports:
      - 5433:5432
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bundle exec puma -C config/puma.rb -e production
    tty: true
    stdin_open: true
    depends_on:
      - db_prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app_name
  web_prod:
    build:
      context: containers/nginx
    ports:
      - 53000:80
    depends_on:
      - app_prod
    volumes:
      - .:/myapp
volumes:
  psgl_data:
